# Automated Build Script for Sintese CLI
# This script builds the executable and sets up the alias in PowerShell profile

Write-Host "=== Sintese CLI - Automated Build Script ===" -ForegroundColor Cyan
Write-Host ""

# Get the script directory (project root)
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ProjectRoot

# 1. Check if virtual environment exists
Write-Host "[1/5] Checking Python virtual environment..." -ForegroundColor Yellow
$VenvPath = Join-Path $ProjectRoot ".venv"
if (-Not (Test-Path $VenvPath)) {
    Write-Host "Error: Virtual environment not found at $VenvPath" -ForegroundColor Red
    exit 1
}
Write-Host " Virtual environment found" -ForegroundColor Green

# 2. Activate virtual environment and check PyInstaller
Write-Host ""
Write-Host "[2/5] Verifying PyInstaller installation..." -ForegroundColor Yellow
$PythonExe = Join-Path $VenvPath "Scripts\python.exe"
$PyInstallerCheck = & $PythonExe -m pip show pyinstaller 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "PyInstaller not found. Installing..." -ForegroundColor Yellow
    & $PythonExe -m pip install pyinstaller
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Error: Failed to install PyInstaller" -ForegroundColor Red
        exit 1
    }
}
Write-Host " PyInstaller is ready" -ForegroundColor Green

# 3. Clean previous build
Write-Host ""
Write-Host "[3/5] Cleaning previous build artifacts..." -ForegroundColor Yellow
$DirsToClean = @("build", "dist")
foreach ($dir in $DirsToClean) {
    $path = Join-Path $ProjectRoot $dir
    if (Test-Path $path) {
        try {
            Remove-Item -Path $path -Recurse -Force -ErrorAction Stop
            Write-Host "  Removed: $dir/" -ForegroundColor Gray
        } catch {
            Write-Host "  Could not remove $path (might be in use). Trying to stop running 'sintese' process..." -ForegroundColor Yellow
            $proc = Get-Process -Name sintese -ErrorAction SilentlyContinue
            if ($proc) {
                try {
                    $proc | Stop-Process -Force -ErrorAction Stop
                    Start-Sleep -Seconds 1
                    Remove-Item -Path $path -Recurse -Force -ErrorAction Stop
                    Write-Host "  Removed after stopping process: $dir/" -ForegroundColor Gray
                } catch {
                    Write-Host ("  Failed to stop process or remove {0}: {1}" -f $path, $_.Exception.Message) -ForegroundColor Red
                }
            } else {
                Write-Host "  No running 'sintese' process found. Could not remove: $path" -ForegroundColor Yellow
            }
        }
    }
}
Write-Host " Build directories cleaned" -ForegroundColor Green

# 4. Build the executable
Write-Host ""
Write-Host "[4/5] Building executable with PyInstaller..." -ForegroundColor Yellow
$SpecFile = Join-Path $ProjectRoot "sintese.spec"

# Use python -m PyInstaller to avoid launcher issues with hardcoded paths
& $PythonExe -m PyInstaller $SpecFile --noconfirm
Write-Host ""

if ($LASTEXITCODE -ne 0) {
    Write-Host "Error: Build failed!" -ForegroundColor Red
    exit 1
}

$ExePath = Join-Path $ProjectRoot "dist\sintese.exe"
if (-Not (Test-Path $ExePath)) {
    Write-Host "Error: Executable not found at $ExePath" -ForegroundColor Red
    exit 1
}
Write-Host " Executable built successfully at: $ExePath" -ForegroundColor Green

# Copy database file to dist folder
$DbSource = Join-Path $ProjectRoot "base.db"
$DbDest = Join-Path $ProjectRoot "dist\base.db"
if (Test-Path $DbSource) {
    Copy-Item -Path $DbSource -Destination $DbDest -Force
    Write-Host " Database copied to dist folder" -ForegroundColor Green
}

# 5. Set up PowerShell alias
Write-Host ""
Write-Host "[5/5] Setting up PowerShell alias..." -ForegroundColor Yellow

# Verify executable path before creating alias
Write-Host "  Verifying executable path: $ExePath" -ForegroundColor Gray
if (-Not (Test-Path $ExePath)) {
    Write-Host "Error: Executable not found at $ExePath" -ForegroundColor Red
    Write-Host "Build may have failed. Check PyInstaller output above." -ForegroundColor Red
    exit 1
}

# Define the alias code block
$AliasCode = @"
# ===== Sintese CLI Alias =====
# Auto-generated by build.ps1
# This creates a 'sintese' function and 's' alias for easy access
function Invoke-Sintese {
    & '$ExePath' @args
}
Set-Alias -Name sintese -Value Invoke-Sintese -Force
Set-Alias -Name s -Value Invoke-Sintese -Force
# ==============================
"@

try {
    # Check if profile exists, create if not
    if (-Not (Test-Path $PROFILE)) {
        Write-Host "  Creating PowerShell profile at: $PROFILE" -ForegroundColor Gray
        $ProfileDir = Split-Path -Parent $PROFILE
        if (-Not (Test-Path $ProfileDir)) {
            New-Item -Path $ProfileDir -ItemType Directory -Force | Out-Null
        }
        New-Item -Path $PROFILE -Type File -Force | Out-Null
    }

    # Remove read-only attribute if present
    if (Test-Path $PROFILE) {
        $fileInfo = Get-Item $PROFILE
        if ($fileInfo.IsReadOnly) {
            Write-Host "  Removing read-only attribute from profile..." -ForegroundColor Gray
            $fileInfo.IsReadOnly = $false
        }
    }

    # Read current profile content
    $ProfileContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
    if (-Not $ProfileContent) { $ProfileContent = "" }

    # Check if alias already exists in profile
    if ($ProfileContent -match "Sintese CLI Alias") {
        Write-Host "  Alias configuration already exists in profile" -ForegroundColor Gray
        Write-Host "  Updating with new path..." -ForegroundColor Gray
        
        # Remove old configuration
        $ProfileContent = $ProfileContent -replace "(?s)# ===== Sintese CLI Alias =====.*?# ==============================\r?\n?", ""
        # Add new configuration
        $ProfileContent = $ProfileContent.TrimEnd() + "`n" + $AliasCode
        Set-Content -Path $PROFILE -Value $ProfileContent -Force
    } else {
        Write-Host "  Adding alias configuration to profile..." -ForegroundColor Gray
        Add-Content -Path $PROFILE -Value $AliasCode -Force
    }

    Write-Host " Alias configured in PowerShell profile" -ForegroundColor Green
    Write-Host "  - Use 'sintese' or 's' to run the application" -ForegroundColor Cyan
} catch {
    Write-Host " Could not modify PowerShell profile automatically" -ForegroundColor Yellow
    Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "  Manual setup required:" -ForegroundColor Yellow
    Write-Host "  1. Open your profile: notepad `$PROFILE" -ForegroundColor Cyan
    Write-Host "  2. Add the following code:" -ForegroundColor Cyan
    Write-Host ""
    Write-Host $AliasCode -ForegroundColor White
    Write-Host ""
}

# Load alias into current session
Write-Host ""
Write-Host "Loading alias into current session..." -ForegroundColor Yellow
try {
    Invoke-Expression $AliasCode
    Write-Host " Alias loaded for current session" -ForegroundColor Green
} catch {
    Write-Host " Could not load alias in current session" -ForegroundColor Yellow
    Write-Host "  You may need to restart PowerShell" -ForegroundColor Gray
}

# 6. Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "BUILD COMPLETE!" -ForegroundColor Green -BackgroundColor Black
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Executable location:" -ForegroundColor White
Write-Host "  $ExePath" -ForegroundColor Cyan
Write-Host ""
Write-Host "To run the application, use:" -ForegroundColor White
Write-Host "  sintese" -ForegroundColor Cyan
Write-Host "  or simply: s" -ForegroundColor Cyan
Write-Host ""
Write-Host "Note: The alias is now available in this session and" -ForegroundColor Gray
Write-Host "      will be automatically loaded in all future PowerShell sessions." -ForegroundColor Gray
Write-Host ""
